### ISSUE TITLE
Colocar dados de keys e urls em variáveis de ambiente

### ISSUE THREAD

**Issue by leandroramos** [uspdev/senhaunica-rails#2]
Colocar os dados sensíveis em variáveis de ambiente do sistema (no Linux mesmo), ou usar uma gem como a Figaro, que coloca as coisas certas no .gitignore e deixa o código mais agnóstico em relação às unidades.

consumer_key
consumer_secret
callback_id, url
e as outras coisas também

**Comment by biamunhoz** [comment]
Resolvido em #4
